language: python
dist: xenial
sudo: true
cache: pip
env: CIBW_SKIP='*-win32 *-manylinux1_i686'
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install -r requirements.txt -q
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then export CIBW_BUILD='cp35*'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then export CIBW_BUILD='cp36*'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then export CIBW_BUILD='cp37*'; fi
  - pip install cibuildwheel==0.10.1
  - cibuildwheel --output-dir wheelhouse
deploy:
  provider: pypi
  user: SimLeek
  skip_existing: true
  password:
    secure: eedRmLVBaBPg+PK2MwpWgAnGz66leCCPUG3P2kIic+Jb8t39Fa0ZRbdWKFVjK/Z4qsc/XCicSyFkGHa/2kKYOmeS5KgSk7RtNQUUtljQtHobniQIUwf+Q6zCIQl3q/sjZExSV9dVTp0lZCeqjU7efN1pI3uLl/y0B4A0k7lxnPGzorJot289WRH8vQmDSYq27VoFeN27SL9tF+8B3rjZvLfqcwT3ZFC6LZyX1Ywwu2KbCqcoa7m/1oUdEV3WBLQWuRNngmbKMiCQZWmLdmwREuo7RORo5/9AArJXcDxZ6dLAqZiXRJUO/F+i+rCcwfl4xNbqFOWaN4mlKueKDCzYb+uCxIzHaysHweoDkTaknXfpOr1ZdFF4aQ/ZH+7xGUj1eKm/5vXkRubfjblqiE4q89hSijbyhOu3OPTp4qIywshXN/cTsusXKdjdDsZlvowo86d0y4Rxu+9Q+AaDs0YgtPxHnfMW2njOBpB8s9rr4vT6aAj3envNDf20BO0t4G2OyDRXHMW02G/Sw+F3+YJKxn90yqWQK+ReIAC6v+aNTQbtn14+Erh+zK/NuFwdyx+2DzFEV44f39RYSckFsdkiYTDHiaJNdy651fzcORVh3bXoFsbUyInKyVYHfybHPc/VgsYCfgBNs6+4v2oG3QjjEDIAvdnBLmDd2vYnJolZ0O8=
