language: python
dist: xenial
sudo: true
cache: pip
env: CIBW_SKIP='*-win32 *-manylinux1_i686'
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install -r requirements.txt -q
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then export CIBW_BUILD='cp35*'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then export CIBW_BUILD='cp36*'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then export CIBW_BUILD='cp37*'; fi
  - pip install cibuildwheel==0.10.1
  - cibuildwheel --output-dir wheelhouse
deploy:
  provider: pypi
  user: SimLeek
  skip_existing: true
  password:
    secure: CZbal/rdhjnfv3kMNL9CIUVi6wappWUpeYDr0N4fkzjf2wAkbHEhdb77+tQwXyMtYPnvaVUfMFkeEaUKI6KwFdgxuQYLlu8WrBi8uOz/0C5P9FR8X/NkgQDlEuu3NBw3pOX5bxdlAjHifp8fg1wORyuo7no7EUolZ10XcAHipTLHDLH/cfweCJGL7BCKy8jhs+Pa+EUCfKe85QJLIXqhVxg4AqtyEIlW146rwvvPlq9RaWmy3gZUMDdDLx+H2DsOGeXIZDQnNWTvBJYhjx4a6vjcFrqysNo0u/Y6qhhYg9mXHm4az5KMeN8KnF3mJiDxjYtfM44o2jfgAQNSg/jcDag8TQhYy8nABxj8veqYJesMTMnM7OsdQ8IuNpJ4W9nE5rAzOzNI2dwEkm08Sw+KxN/QPZyxCmMCzxkW/TDCS9WjvHjEjo3tYOm/QpX9Ig4Dm9HA/KsZY19suvuQa36+QLAr0MTq+Dx/81BEivVKy1j8srBE+cvgDo5xQ0ZB3OZNgDp7GXoVhYzTnLQaf0Ez6PHzmlesSBTuXzPbePnsW/cmXSNd2RJrU9PkfmvKW0Foc84m6ctRwM/n2S20kdIYPtzhq1kG8Dnz3WbuATcAgtd5ThFtlFh6FsRE9nq3c9jFfiPDOLPzL9OZxeYENmNN09uC01nKQ/8fiH2IbXhNICE=
